### ISSUE TITLE
Knapsack problem

### ISSUE THREAD

**Issue by e10jon** [brg8/opl#1]
I'm putting together a fantasy sports engine, and I need help coding the algorithm that selects players with the most value, constrained by price, and constrained by position.

If you'd like to assist me, I'd be willing to Venmo or Paypal you some money. 

If you're not interested, can you point me down the right path? Thank you!

**Comment by brg8** [comment]
Hi Ethan,

Happy to take a look at the very least.

Send me over more information.
- Ben

**Comment by czahor** [comment]
Will do. Contact me directly via email and I'll tell you all about it. ethanczahor@gmail.com
